# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modeller_mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1953, 983)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(100, 0))
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks|QtGui.QMainWindow.ForceTabbedDocks|QtGui.QMainWindow.VerticalTabs)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 1111, 38))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 4, 0, 4)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelOntology = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelOntology.sizePolicy().hasHeightForWidth())
        self.labelOntology.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelOntology.setFont(font)
        self.labelOntology.setObjectName(_fromUtf8("labelOntology"))
        self.horizontalLayout.addWidget(self.labelOntology)
        self.labelModel = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelModel.sizePolicy().hasHeightForWidth())
        self.labelModel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.labelModel.setFont(font)
        self.labelModel.setObjectName(_fromUtf8("labelModel"))
        self.horizontalLayout.addWidget(self.labelModel)
        self.graphicsView = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 60, 1121, 880))
        self.graphicsView.setMinimumSize(QtCore.QSize(750, 0))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidgetMain = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetMain.sizePolicy().hasHeightForWidth())
        self.dockWidgetMain.setSizePolicy(sizePolicy)
        self.dockWidgetMain.setMinimumSize(QtCore.QSize(730, 346))
        self.dockWidgetMain.setFloating(False)
        self.dockWidgetMain.setFeatures(QtGui.QDockWidget.NoDockWidgetFeatures)
        self.dockWidgetMain.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea)
        self.dockWidgetMain.setObjectName(_fromUtf8("dockWidgetMain"))
        self.dockWidgetContents = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        self.dockWidgetContents.setMinimumSize(QtCore.QSize(730, 0))
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.groupBox = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 451, 201))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayoutWidget = QtGui.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 40, 141, 151))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formKeyAutomaton = QtGui.QFormLayout(self.formLayoutWidget)
        self.formKeyAutomaton.setMargin(0)
        self.formKeyAutomaton.setObjectName(_fromUtf8("formKeyAutomaton"))
        self.layoutWidget1 = QtGui.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(200, 40, 250, 92))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.labelObject = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelObject.sizePolicy().hasHeightForWidth())
        self.labelObject.setSizePolicy(sizePolicy)
        self.labelObject.setMinimumSize(QtCore.QSize(120, 20))
        self.labelObject.setAlignment(QtCore.Qt.AlignCenter)
        self.labelObject.setObjectName(_fromUtf8("labelObject"))
        self.horizontalLayout_5.addWidget(self.labelObject)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.pixmapCursor = QtGui.QLabel(self.layoutWidget1)
        self.pixmapCursor.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pixmapCursor.sizePolicy().hasHeightForWidth())
        self.pixmapCursor.setSizePolicy(sizePolicy)
        self.pixmapCursor.setMinimumSize(QtCore.QSize(32, 32))
        self.pixmapCursor.setFrameShadow(QtGui.QFrame.Sunken)
        self.pixmapCursor.setText(_fromUtf8(""))
        self.pixmapCursor.setTextFormat(QtCore.Qt.PlainText)
        self.pixmapCursor.setScaledContents(True)
        self.pixmapCursor.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.pixmapCursor.setObjectName(_fromUtf8("pixmapCursor"))
        self.horizontalLayout_3.addWidget(self.pixmapCursor)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.labelLeft = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLeft.sizePolicy().hasHeightForWidth())
        self.labelLeft.setSizePolicy(sizePolicy)
        self.labelLeft.setMinimumSize(QtCore.QSize(100, 20))
        self.labelLeft.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLeft.setObjectName(_fromUtf8("labelLeft"))
        self.horizontalLayout_2.addWidget(self.labelLeft)
        self.labelRight = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelRight.sizePolicy().hasHeightForWidth())
        self.labelRight.setSizePolicy(sizePolicy)
        self.labelRight.setMinimumSize(QtCore.QSize(100, 20))
        self.labelRight.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRight.setObjectName(_fromUtf8("labelRight"))
        self.horizontalLayout_2.addWidget(self.labelRight)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.groupBoxMainControl = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBoxMainControl.setGeometry(QtCore.QRect(510, 10, 211, 141))
        self.groupBoxMainControl.setObjectName(_fromUtf8("groupBoxMainControl"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.groupBoxMainControl)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 92, 111))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.pushSave = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.pushSave.setEnabled(True)
        self.pushSave.setMinimumSize(QtCore.QSize(0, 30))
        self.pushSave.setObjectName(_fromUtf8("pushSave"))
        self.verticalLayout_3.addWidget(self.pushSave)
        self.pushSaveAs = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.pushSaveAs.setEnabled(True)
        self.pushSaveAs.setMinimumSize(QtCore.QSize(0, 30))
        self.pushSaveAs.setObjectName(_fromUtf8("pushSaveAs"))
        self.verticalLayout_3.addWidget(self.pushSaveAs)
        self.pushExit = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.pushExit.setMinimumSize(QtCore.QSize(0, 30))
        self.pushExit.setObjectName(_fromUtf8("pushExit"))
        self.verticalLayout_3.addWidget(self.pushExit)
        self.layoutWidget_2 = QtGui.QWidget(self.dockWidgetContents)
        self.layoutWidget_2.setGeometry(QtCore.QRect(220, 220, 501, 31))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.formLayout_3 = QtGui.QFormLayout(self.layoutWidget_2)
        self.formLayout_3.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setMargin(0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.pushSchnipsel = QtGui.QPushButton(self.layoutWidget_2)
        self.pushSchnipsel.setObjectName(_fromUtf8("pushSchnipsel"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.pushSchnipsel)
        self.labelSchnipsel = QtGui.QLabel(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSchnipsel.sizePolicy().hasHeightForWidth())
        self.labelSchnipsel.setSizePolicy(sizePolicy)
        self.labelSchnipsel.setText(_fromUtf8(""))
        self.labelSchnipsel.setObjectName(_fromUtf8("labelSchnipsel"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.labelSchnipsel)
        self.widgetInteraction = QtGui.QWidget(self.dockWidgetContents)
        self.widgetInteraction.setGeometry(QtCore.QRect(0, 280, 721, 641))
        self.widgetInteraction.setObjectName(_fromUtf8("widgetInteraction"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.widgetInteraction)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 230, 701, 221))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.layoutInteractiveWidgetBottom = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.layoutInteractiveWidgetBottom.setMargin(0)
        self.layoutInteractiveWidgetBottom.setObjectName(_fromUtf8("layoutInteractiveWidgetBottom"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.widgetInteraction)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 10, 211, 221))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.layoutInteractiveWidgetTop = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.layoutInteractiveWidgetTop.setMargin(0)
        self.layoutInteractiveWidgetTop.setObjectName(_fromUtf8("layoutInteractiveWidgetTop"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.widgetInteraction)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(240, 10, 401, 221))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.layoutNetworks = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.layoutNetworks.setMargin(0)
        self.layoutNetworks.setObjectName(_fromUtf8("layoutNetworks"))
        self.groupBoxNamedNetworks = QtGui.QGroupBox(self.widgetInteraction)
        self.groupBoxNamedNetworks.setGeometry(QtCore.QRect(650, 19, 71, 171))
        self.groupBoxNamedNetworks.setObjectName(_fromUtf8("groupBoxNamedNetworks"))
        self.pushAddNamedNetwork = QtGui.QPushButton(self.groupBoxNamedNetworks)
        self.pushAddNamedNetwork.setGeometry(QtCore.QRect(0, 30, 61, 29))
        self.pushAddNamedNetwork.setObjectName(_fromUtf8("pushAddNamedNetwork"))
        self.pushEditNamedNetwork = QtGui.QPushButton(self.groupBoxNamedNetworks)
        self.pushEditNamedNetwork.setGeometry(QtCore.QRect(0, 60, 61, 29))
        self.pushEditNamedNetwork.setObjectName(_fromUtf8("pushEditNamedNetwork"))
        self.pushDeleteNamedNetwork = QtGui.QPushButton(self.groupBoxNamedNetworks)
        self.pushDeleteNamedNetwork.setGeometry(QtCore.QRect(0, 90, 61, 29))
        self.pushDeleteNamedNetwork.setObjectName(_fromUtf8("pushDeleteNamedNetwork"))
        self.layoutWidget2 = QtGui.QWidget(self.dockWidgetContents)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 220, 171, 31))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.layoutEditorPhase = QtGui.QVBoxLayout(self.layoutWidget2)
        self.layoutEditorPhase.setMargin(0)
        self.layoutEditorPhase.setObjectName(_fromUtf8("layoutEditorPhase"))
        self.comboEditorPhase = QtGui.QComboBox(self.layoutWidget2)
        self.comboEditorPhase.setObjectName(_fromUtf8("comboEditorPhase"))
        self.layoutEditorPhase.addWidget(self.comboEditorPhase)
        self.textStatus = QtGui.QPlainTextEdit(self.dockWidgetContents)
        self.textStatus.setGeometry(QtCore.QRect(220, 150, 501, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(166, 162, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.textStatus.setPalette(palette)
        self.textStatus.setObjectName(_fromUtf8("textStatus"))
        self.dockWidgetMain.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidgetMain)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setOrientation(QtCore.Qt.Vertical)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.dockWidgetLogger = QtGui.QDockWidget(MainWindow)
        self.dockWidgetLogger.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea)
        self.dockWidgetLogger.setObjectName(_fromUtf8("dockWidgetLogger"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.dockWidgetLogger.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidgetLogger)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Process Modeller", None))
        self.labelOntology.setText(_translate("MainWindow", "ontology", None))
        self.labelModel.setText(_translate("MainWindow", "model      ", None))
        self.dockWidgetMain.setWindowTitle(_translate("MainWindow", "main", None))
        self.groupBox.setTitle(_translate("MainWindow", "Navigation", None))
        self.labelObject.setText(_translate("MainWindow", "object", None))
        self.labelLeft.setText(_translate("MainWindow", "left", None))
        self.labelRight.setText(_translate("MainWindow", "right", None))
        self.groupBoxMainControl.setTitle(_translate("MainWindow", "controls", None))
        self.pushSave.setText(_translate("MainWindow", "save", None))
        self.pushSaveAs.setText(_translate("MainWindow", "save as", None))
        self.pushExit.setText(_translate("MainWindow", "exit", None))
        self.pushSchnipsel.setText(_translate("MainWindow", "schnipsel", None))
        self.groupBoxNamedNetworks.setTitle(_translate("MainWindow", "edit", None))
        self.pushAddNamedNetwork.setText(_translate("MainWindow", "add", None))
        self.pushEditNamedNetwork.setText(_translate("MainWindow", "edit", None))
        self.pushDeleteNamedNetwork.setText(_translate("MainWindow", "delete", None))
        self.dockWidgetLogger.setWindowTitle(_translate("MainWindow", "logger", None))

