# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editor_initialise_system_gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1015, 537)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.message_box = QtWidgets.QTextBrowser(self.centralwidget)
        self.message_box.setGeometry(QtCore.QRect(50, 410, 491, 61))
        self.message_box.setObjectName("message_box")
        self.select_named_network = QtWidgets.QComboBox(self.centralwidget)
        self.select_named_network.setGeometry(QtCore.QRect(740, 60, 211, 25))
        self.select_named_network.setObjectName("select_named_network")
        self.ontology_name_label = QtWidgets.QLabel(self.centralwidget)
        self.ontology_name_label.setGeometry(QtCore.QRect(0, 0, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.ontology_name_label.setFont(font)
        self.ontology_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ontology_name_label.setObjectName("ontology_name_label")
        self.model_name_label = QtWidgets.QLabel(self.centralwidget)
        self.model_name_label.setGeometry(QtCore.QRect(290, 0, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.model_name_label.setFont(font)
        self.model_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.model_name_label.setObjectName("model_name_label")
        self.save_model_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_model_button.setGeometry(QtCore.QRect(790, 410, 141, 25))
        self.save_model_button.setObjectName("save_model_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(750, 40, 131, 17))
        self.label.setObjectName("label")
        self.display_topology = QtWidgets.QGraphicsView(self.centralwidget)
        self.display_topology.setGeometry(QtCore.QRect(50, 40, 491, 361))
        self.display_topology.setObjectName("display_topology")
        self.initialise_system_button = QtWidgets.QPushButton(self.centralwidget)
        self.initialise_system_button.setGeometry(QtCore.QRect(790, 360, 141, 25))
        self.initialise_system_button.setObjectName("initialise_system_button")
        self.select_group = QtWidgets.QComboBox(self.centralwidget)
        self.select_group.setGeometry(QtCore.QRect(740, 120, 211, 25))
        self.select_group.setObjectName("select_group")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(750, 100, 131, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(750, 170, 151, 17))
        self.label_3.setObjectName("label_3")
        self.select_single = QtWidgets.QComboBox(self.centralwidget)
        self.select_single.setGeometry(QtCore.QRect(740, 190, 211, 25))
        self.select_single.setObjectName("select_single")
        self.case_name_label = QtWidgets.QLabel(self.centralwidget)
        self.case_name_label.setGeometry(QtCore.QRect(630, 0, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.case_name_label.setFont(font)
        self.case_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.case_name_label.setObjectName("case_name_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1015, 22))
        self.menubar.setObjectName("menubar")
        self.menuModel_Factory = QtWidgets.QMenu(self.menubar)
        self.menuModel_Factory.setObjectName("menuModel_Factory")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionInitialise = QtWidgets.QAction(MainWindow)
        self.actionInitialise.setObjectName("actionInitialise")
        self.menuModel_Factory.addAction(self.actionInitialise)
        self.menubar.addAction(self.menuModel_Factory.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ontology_name_label.setText(_translate("MainWindow", "TextLabel"))
        self.model_name_label.setText(_translate("MainWindow", "TextLabel"))
        self.save_model_button.setText(_translate("MainWindow", "Save file"))
        self.label.setText(_translate("MainWindow", "Named network"))
        self.initialise_system_button.setText(_translate("MainWindow", "Initialise system"))
        self.label_2.setText(_translate("MainWindow", "Select group"))
        self.label_3.setText(_translate("MainWindow", "Single nodes or arcs"))
        self.case_name_label.setText(_translate("MainWindow", "TextLabel"))
        self.menuModel_Factory.setTitle(_translate("MainWindow", "Model Factory"))
        self.actionInitialise.setText(_translate("MainWindow", "Initialise"))
