# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editor_graphcomponents_gui.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1624, 968)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupComponents = QtGui.QGroupBox(self.centralwidget)
        self.groupComponents.setGeometry(QtCore.QRect(390, 0, 391, 911))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 228, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 228, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 228, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 228, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.groupComponents.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupComponents.setFont(font)
        self.groupComponents.setAutoFillBackground(True)
        self.groupComponents.setObjectName(_fromUtf8("groupComponents"))
        self.groupShapes = QtGui.QGroupBox(self.groupComponents)
        self.groupShapes.setGeometry(QtCore.QRect(10, 450, 371, 81))
        self.groupShapes.setObjectName(_fromUtf8("groupShapes"))
        self.listComponents = QtGui.QListWidget(self.groupShapes)
        self.listComponents.setGeometry(QtCore.QRect(110, 20, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.listComponents.setFont(font)
        self.listComponents.setObjectName(_fromUtf8("listComponents"))
        self.groupObjects = QtGui.QGroupBox(self.groupComponents)
        self.groupObjects.setGeometry(QtCore.QRect(10, 530, 371, 371))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupObjects.setFont(font)
        self.groupObjects.setObjectName(_fromUtf8("groupObjects"))
        self.listRootObjects = QtGui.QListWidget(self.groupObjects)
        self.listRootObjects.setGeometry(QtCore.QRect(110, 20, 261, 331))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.listRootObjects.setFont(font)
        self.listRootObjects.setObjectName(_fromUtf8("listRootObjects"))
        self.groupPhase = QtGui.QGroupBox(self.groupComponents)
        self.groupPhase.setGeometry(QtCore.QRect(10, 400, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupPhase.setFont(font)
        self.groupPhase.setObjectName(_fromUtf8("groupPhase"))
        self.comboEditorPhase = QtGui.QComboBox(self.groupPhase)
        self.comboEditorPhase.setGeometry(QtCore.QRect(110, 20, 261, 31))
        self.comboEditorPhase.setObjectName(_fromUtf8("comboEditorPhase"))
        self.layoutWidget = QtGui.QWidget(self.groupComponents)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 30, 329, 31))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.radioButtonNetworksComponents = QtGui.QRadioButton(self.layoutWidget)
        self.radioButtonNetworksComponents.setObjectName(_fromUtf8("radioButtonNetworksComponents"))
        self.horizontalLayout.addWidget(self.radioButtonNetworksComponents)
        self.radioButtonInterfacesComponents = QtGui.QRadioButton(self.layoutWidget)
        self.radioButtonInterfacesComponents.setObjectName(_fromUtf8("radioButtonInterfacesComponents"))
        self.horizontalLayout.addWidget(self.radioButtonInterfacesComponents)
        self.radioButtonIntrafacesComponents = QtGui.QRadioButton(self.layoutWidget)
        self.radioButtonIntrafacesComponents.setObjectName(_fromUtf8("radioButtonIntrafacesComponents"))
        self.horizontalLayout.addWidget(self.radioButtonIntrafacesComponents)
        self.groupNetworksComponents = QtGui.QGroupBox(self.groupComponents)
        self.groupNetworksComponents.setGeometry(QtCore.QRect(10, 100, 371, 211))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupNetworksComponents.setFont(font)
        self.groupNetworksComponents.setObjectName(_fromUtf8("groupNetworksComponents"))
        self.listNetworksComponents = QtGui.QListWidget(self.groupNetworksComponents)
        self.listNetworksComponents.setGeometry(QtCore.QRect(10, 30, 361, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.listNetworksComponents.setFont(font)
        self.listNetworksComponents.setObjectName(_fromUtf8("listNetworksComponents"))
        self.groupComponentEditor = QtGui.QGroupBox(self.centralwidget)
        self.groupComponentEditor.setGeometry(QtCore.QRect(780, 0, 831, 921))
        self.groupComponentEditor.setObjectName(_fromUtf8("groupComponentEditor"))
        self.stackedProperties = QtGui.QStackedWidget(self.groupComponentEditor)
        self.stackedProperties.setGeometry(QtCore.QRect(30, 240, 431, 321))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 210, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 210, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 210, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 210, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.stackedProperties.setPalette(palette)
        self.stackedProperties.setObjectName(_fromUtf8("stackedProperties"))
        self.page_ampty = QtGui.QWidget()
        self.page_ampty.setObjectName(_fromUtf8("page_ampty"))
        self.label_31 = QtGui.QLabel(self.page_ampty)
        self.label_31.setGeometry(QtCore.QRect(20, 20, 121, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.stackedProperties.addWidget(self.page_ampty)
        self.page_ellipse = QtGui.QWidget()
        self.page_ellipse.setObjectName(_fromUtf8("page_ellipse"))
        self.spinEllipseWidth = QtGui.QSpinBox(self.page_ellipse)
        self.spinEllipseWidth.setGeometry(QtCore.QRect(210, 50, 55, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.spinEllipseWidth.setFont(font)
        self.spinEllipseWidth.setObjectName(_fromUtf8("spinEllipseWidth"))
        self.spinEllipseHeight = QtGui.QSpinBox(self.page_ellipse)
        self.spinEllipseHeight.setGeometry(QtCore.QRect(210, 90, 55, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.spinEllipseHeight.setFont(font)
        self.spinEllipseHeight.setObjectName(_fromUtf8("spinEllipseHeight"))
        self.label_32 = QtGui.QLabel(self.page_ellipse)
        self.label_32.setGeometry(QtCore.QRect(20, 30, 62, 18))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.label_33 = QtGui.QLabel(self.page_ellipse)
        self.label_33.setGeometry(QtCore.QRect(150, 50, 41, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.label_34 = QtGui.QLabel(self.page_ellipse)
        self.label_34.setGeometry(QtCore.QRect(150, 90, 51, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.groupBoxEllipseColour = QtGui.QGroupBox(self.page_ellipse)
        self.groupBoxEllipseColour.setGeometry(QtCore.QRect(210, 140, 51, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 121, 121))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 161, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 121, 121))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 161, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 121, 121))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 121, 121))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 161, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 121, 121))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 121, 121))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.groupBoxEllipseColour.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBoxEllipseColour.setFont(font)
        self.groupBoxEllipseColour.setObjectName(_fromUtf8("groupBoxEllipseColour"))
        self.toolEllipseColour = QtGui.QToolButton(self.groupBoxEllipseColour)
        self.toolEllipseColour.setGeometry(QtCore.QRect(10, 20, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.toolEllipseColour.setFont(font)
        self.toolEllipseColour.setText(_fromUtf8(""))
        self.toolEllipseColour.setAutoRaise(False)
        self.toolEllipseColour.setObjectName(_fromUtf8("toolEllipseColour"))
        self.stackedProperties.addWidget(self.page_ellipse)
        self.page_line = QtGui.QWidget()
        self.page_line.setObjectName(_fromUtf8("page_line"))
        self.label_35 = QtGui.QLabel(self.page_line)
        self.label_35.setGeometry(QtCore.QRect(60, 60, 62, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.spinLineWidth = QtGui.QSpinBox(self.page_line)
        self.spinLineWidth.setGeometry(QtCore.QRect(224, 120, 81, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.spinLineWidth.setFont(font)
        self.spinLineWidth.setObjectName(_fromUtf8("spinLineWidth"))
        self.comboLineStyle = QtGui.QComboBox(self.page_line)
        self.comboLineStyle.setGeometry(QtCore.QRect(220, 70, 85, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.comboLineStyle.setFont(font)
        self.comboLineStyle.setObjectName(_fromUtf8("comboLineStyle"))
        self.groupBoxLineColour = QtGui.QGroupBox(self.page_line)
        self.groupBoxLineColour.setGeometry(QtCore.QRect(250, 170, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBoxLineColour.setFont(font)
        self.groupBoxLineColour.setObjectName(_fromUtf8("groupBoxLineColour"))
        self.toolLineColour = QtGui.QToolButton(self.groupBoxLineColour)
        self.toolLineColour.setGeometry(QtCore.QRect(10, 20, 31, 25))
        self.toolLineColour.setText(_fromUtf8(""))
        self.toolLineColour.setObjectName(_fromUtf8("toolLineColour"))
        self.label_36 = QtGui.QLabel(self.page_line)
        self.label_36.setGeometry(QtCore.QRect(160, 120, 41, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.label_37 = QtGui.QLabel(self.page_line)
        self.label_37.setGeometry(QtCore.QRect(160, 70, 41, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_37.setFont(font)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.stackedProperties.addWidget(self.page_line)
        self.page_text = QtGui.QWidget()
        self.page_text.setObjectName(_fromUtf8("page_text"))
        self.label_38 = QtGui.QLabel(self.page_text)
        self.label_38.setGeometry(QtCore.QRect(50, 40, 62, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.stackedProperties.addWidget(self.page_text)
        self.page_panel = QtGui.QWidget()
        self.page_panel.setObjectName(_fromUtf8("page_panel"))
        self.label_39 = QtGui.QLabel(self.page_panel)
        self.label_39.setGeometry(QtCore.QRect(60, 50, 62, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.groupBoxPanelColour = QtGui.QGroupBox(self.page_panel)
        self.groupBoxPanelColour.setGeometry(QtCore.QRect(280, 170, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBoxPanelColour.setFont(font)
        self.groupBoxPanelColour.setObjectName(_fromUtf8("groupBoxPanelColour"))
        self.toolPanelColour = QtGui.QToolButton(self.groupBoxPanelColour)
        self.toolPanelColour.setGeometry(QtCore.QRect(10, 20, 31, 25))
        self.toolPanelColour.setText(_fromUtf8(""))
        self.toolPanelColour.setObjectName(_fromUtf8("toolPanelColour"))
        self.layoutWidget1 = QtGui.QWidget(self.page_panel)
        self.layoutWidget1.setGeometry(QtCore.QRect(130, 60, 201, 92))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 10, 0, 10)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_49 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_49.setFont(font)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout.addWidget(self.label_49, 0, 0, 1, 1)
        self.spinPanelWidth = QtGui.QSpinBox(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinPanelWidth.sizePolicy().hasHeightForWidth())
        self.spinPanelWidth.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.spinPanelWidth.setFont(font)
        self.spinPanelWidth.setMaximum(2000)
        self.spinPanelWidth.setObjectName(_fromUtf8("spinPanelWidth"))
        self.gridLayout.addWidget(self.spinPanelWidth, 0, 1, 1, 1)
        self.label_40 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_40.setFont(font)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout.addWidget(self.label_40, 1, 0, 1, 1)
        self.spinPanelHeight = QtGui.QSpinBox(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinPanelHeight.sizePolicy().hasHeightForWidth())
        self.spinPanelHeight.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.spinPanelHeight.setFont(font)
        self.spinPanelHeight.setMaximum(2000)
        self.spinPanelHeight.setObjectName(_fromUtf8("spinPanelHeight"))
        self.gridLayout.addWidget(self.spinPanelHeight, 1, 1, 1, 1)
        self.stackedProperties.addWidget(self.page_panel)
        self.groupPosition = QtGui.QGroupBox(self.groupComponentEditor)
        self.groupPosition.setGeometry(QtCore.QRect(30, 140, 431, 80))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 207, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 207, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 207, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 207, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.groupPosition.setPalette(palette)
        self.groupPosition.setAutoFillBackground(True)
        self.groupPosition.setObjectName(_fromUtf8("groupPosition"))
        self.spinRelPositionX = QtGui.QSpinBox(self.groupPosition)
        self.spinRelPositionX.setGeometry(QtCore.QRect(55, 31, 61, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.spinRelPositionX.setFont(font)
        self.spinRelPositionX.setMinimum(-100)
        self.spinRelPositionX.setMaximum(100)
        self.spinRelPositionX.setObjectName(_fromUtf8("spinRelPositionX"))
        self.spinRelPositionY = QtGui.QSpinBox(self.groupPosition)
        self.spinRelPositionY.setGeometry(QtCore.QRect(155, 31, 61, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.spinRelPositionY.setFont(font)
        self.spinRelPositionY.setMinimum(-100)
        self.spinRelPositionY.setMaximum(100)
        self.spinRelPositionY.setObjectName(_fromUtf8("spinRelPositionY"))
        self.label_45 = QtGui.QLabel(self.groupPosition)
        self.label_45.setGeometry(QtCore.QRect(41, 31, 16, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_45.setFont(font)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.label_46 = QtGui.QLabel(self.groupPosition)
        self.label_46.setGeometry(QtCore.QRect(141, 31, 16, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_46.setFont(font)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.checkMovable = QtGui.QCheckBox(self.groupPosition)
        self.checkMovable.setGeometry(QtCore.QRect(300, 25, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkMovable.setFont(font)
        self.checkMovable.setObjectName(_fromUtf8("checkMovable"))
        self.groupActions = QtGui.QGroupBox(self.groupComponentEditor)
        self.groupActions.setGeometry(QtCore.QRect(510, 560, 331, 351))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 215, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 235, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 107, 119))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(147, 143, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 215, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 235, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 215, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 235, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 107, 119))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(147, 143, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 215, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 235, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 107, 119))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 215, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(237, 235, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 107, 119))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(147, 143, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 107, 119))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 107, 119))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 215, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 215, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 215, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.groupActions.setPalette(palette)
        self.groupActions.setAutoFillBackground(True)
        self.groupActions.setObjectName(_fromUtf8("groupActions"))
        self.listAvailableActions = QtGui.QListWidget(self.groupActions)
        self.listAvailableActions.setGeometry(QtCore.QRect(20, 40, 131, 241))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.listAvailableActions.setFont(font)
        self.listAvailableActions.setObjectName(_fromUtf8("listAvailableActions"))
        self.listAssignedActions = QtGui.QListWidget(self.groupActions)
        self.listAssignedActions.setGeometry(QtCore.QRect(180, 40, 131, 241))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.listAssignedActions.setFont(font)
        self.listAssignedActions.setObjectName(_fromUtf8("listAssignedActions"))
        self.label_47 = QtGui.QLabel(self.groupActions)
        self.label_47.setGeometry(QtCore.QRect(50, 20, 71, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_47.setFont(font)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.label_48 = QtGui.QLabel(self.groupActions)
        self.label_48.setGeometry(QtCore.QRect(210, 20, 71, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_48.setFont(font)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.pushExplainActions = QtGui.QPushButton(self.groupActions)
        self.pushExplainActions.setGeometry(QtCore.QRect(120, 290, 99, 27))
        self.pushExplainActions.setObjectName(_fromUtf8("pushExplainActions"))
        self.groupLayer = QtGui.QGroupBox(self.groupComponentEditor)
        self.groupLayer.setGeometry(QtCore.QRect(500, 140, 331, 321))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 245, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 245, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 245, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 245, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.groupLayer.setPalette(palette)
        self.groupLayer.setAutoFillBackground(True)
        self.groupLayer.setObjectName(_fromUtf8("groupLayer"))
        self.layoutWidget2 = QtGui.QWidget(self.groupLayer)
        self.layoutWidget2.setGeometry(QtCore.QRect(180, 20, 131, 276))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.radioMainPanel = QtGui.QRadioButton(self.layoutWidget2)
        self.radioMainPanel.setObjectName(_fromUtf8("radioMainPanel"))
        self.verticalLayout.addWidget(self.radioMainPanel)
        self.radioSidePanel = QtGui.QRadioButton(self.layoutWidget2)
        self.radioSidePanel.setObjectName(_fromUtf8("radioSidePanel"))
        self.verticalLayout.addWidget(self.radioSidePanel)
        self.radioNetwork = QtGui.QRadioButton(self.layoutWidget2)
        self.radioNetwork.setObjectName(_fromUtf8("radioNetwork"))
        self.verticalLayout.addWidget(self.radioNetwork)
        self.radioArc = QtGui.QRadioButton(self.layoutWidget2)
        self.radioArc.setObjectName(_fromUtf8("radioArc"))
        self.verticalLayout.addWidget(self.radioArc)
        self.radioKnot = QtGui.QRadioButton(self.layoutWidget2)
        self.radioKnot.setObjectName(_fromUtf8("radioKnot"))
        self.verticalLayout.addWidget(self.radioKnot)
        self.radioNode = QtGui.QRadioButton(self.layoutWidget2)
        self.radioNode.setObjectName(_fromUtf8("radioNode"))
        self.verticalLayout.addWidget(self.radioNode)
        self.radioProperty = QtGui.QRadioButton(self.layoutWidget2)
        self.radioProperty.setObjectName(_fromUtf8("radioProperty"))
        self.verticalLayout.addWidget(self.radioProperty)
        self.radioText = QtGui.QRadioButton(self.layoutWidget2)
        self.radioText.setObjectName(_fromUtf8("radioText"))
        self.verticalLayout.addWidget(self.radioText)
        self.groupStateApplication = QtGui.QGroupBox(self.groupComponentEditor)
        self.groupStateApplication.setGeometry(QtCore.QRect(20, 40, 441, 81))
        self.groupStateApplication.setObjectName(_fromUtf8("groupStateApplication"))
        self.label_29 = QtGui.QLabel(self.groupStateApplication)
        self.label_29.setGeometry(QtCore.QRect(20, 30, 121, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_28 = QtGui.QLabel(self.groupStateApplication)
        self.label_28.setGeometry(QtCore.QRect(220, 30, 121, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.comboState = QtGui.QComboBox(self.groupStateApplication)
        self.comboState.setGeometry(QtCore.QRect(10, 50, 181, 27))
        self.comboState.setObjectName(_fromUtf8("comboState"))
        self.comboApplication = QtGui.QComboBox(self.groupStateApplication)
        self.comboApplication.setGeometry(QtCore.QRect(220, 50, 221, 27))
        self.comboApplication.setObjectName(_fromUtf8("comboApplication"))
        self.Logger = QtGui.QTextBrowser(self.groupComponentEditor)
        self.Logger.setGeometry(QtCore.QRect(30, 580, 431, 331))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Logger.setFont(font)
        self.Logger.setObjectName(_fromUtf8("Logger"))
        self.groupNetworks = QtGui.QGroupBox(self.centralwidget)
        self.groupNetworks.setGeometry(QtCore.QRect(0, 610, 321, 291))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupNetworks.setFont(font)
        self.groupNetworks.setObjectName(_fromUtf8("groupNetworks"))
        self.listNetworks = QtGui.QListWidget(self.groupNetworks)
        self.listNetworks.setGeometry(QtCore.QRect(10, 80, 301, 171))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.listNetworks.setFont(font)
        self.listNetworks.setObjectName(_fromUtf8("listNetworks"))
        self.groupBoxNetworkColour = QtGui.QGroupBox(self.groupNetworks)
        self.groupBoxNetworkColour.setGeometry(QtCore.QRect(140, 10, 51, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 121, 121))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 161, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 121, 121))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 161, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 121, 121))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 121, 121))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 161, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 121, 121))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 121, 121))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.groupBoxNetworkColour.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBoxNetworkColour.setFont(font)
        self.groupBoxNetworkColour.setObjectName(_fromUtf8("groupBoxNetworkColour"))
        self.toolNetworkColour = QtGui.QToolButton(self.groupBoxNetworkColour)
        self.toolNetworkColour.setGeometry(QtCore.QRect(10, 20, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.toolNetworkColour.setFont(font)
        self.toolNetworkColour.setText(_fromUtf8(""))
        self.toolNetworkColour.setAutoRaise(False)
        self.toolNetworkColour.setObjectName(_fromUtf8("toolNetworkColour"))
        self.groupControls = QtGui.QGroupBox(self.centralwidget)
        self.groupControls.setGeometry(QtCore.QRect(0, 140, 331, 141))
        self.groupControls.setObjectName(_fromUtf8("groupControls"))
        self.pushCopyPhaseToPhases = QtGui.QPushButton(self.groupControls)
        self.pushCopyPhaseToPhases.setGeometry(QtCore.QRect(0, 60, 92, 28))
        self.pushCopyPhaseToPhases.setObjectName(_fromUtf8("pushCopyPhaseToPhases"))
        self.pushSave = QtGui.QPushButton(self.groupControls)
        self.pushSave.setGeometry(QtCore.QRect(0, 20, 92, 28))
        self.pushSave.setObjectName(_fromUtf8("pushSave"))
        self.pushSaveBackup = QtGui.QPushButton(self.groupControls)
        self.pushSaveBackup.setGeometry(QtCore.QRect(120, 20, 92, 28))
        self.pushSaveBackup.setObjectName(_fromUtf8("pushSaveBackup"))
        self.labelOntology = QtGui.QLabel(self.centralwidget)
        self.labelOntology.setGeometry(QtCore.QRect(10, 0, 371, 17))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.labelOntology.setFont(font)
        self.labelOntology.setObjectName(_fromUtf8("labelOntology"))
        self.groupTokens = QtGui.QGroupBox(self.centralwidget)
        self.groupTokens.setGeometry(QtCore.QRect(10, 320, 321, 271))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupTokens.setFont(font)
        self.groupTokens.setObjectName(_fromUtf8("groupTokens"))
        self.listTokens = QtGui.QListWidget(self.groupTokens)
        self.listTokens.setGeometry(QtCore.QRect(10, 90, 301, 151))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.listTokens.setFont(font)
        self.listTokens.setObjectName(_fromUtf8("listTokens"))
        self.groupBoxTokenColour = QtGui.QGroupBox(self.groupTokens)
        self.groupBoxTokenColour.setGeometry(QtCore.QRect(140, 20, 51, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 121, 121))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 161, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 121, 121))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 161, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 121, 121))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 121, 121))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 161, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 121, 121))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(121, 121, 121))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 242, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.groupBoxTokenColour.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBoxTokenColour.setFont(font)
        self.groupBoxTokenColour.setObjectName(_fromUtf8("groupBoxTokenColour"))
        self.toolTokenColour = QtGui.QToolButton(self.groupBoxTokenColour)
        self.toolTokenColour.setGeometry(QtCore.QRect(10, 20, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.toolTokenColour.setFont(font)
        self.toolTokenColour.setText(_fromUtf8(""))
        self.toolTokenColour.setAutoRaise(False)
        self.toolTokenColour.setObjectName(_fromUtf8("toolTokenColour"))
        self.groupMain = QtGui.QGroupBox(self.centralwidget)
        self.groupMain.setGeometry(QtCore.QRect(0, 20, 361, 91))
        self.groupMain.setObjectName(_fromUtf8("groupMain"))
        self.layoutWidget3 = QtGui.QWidget(self.groupMain)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 20, 341, 66))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.radioButtonTokens = QtGui.QRadioButton(self.layoutWidget3)
        self.radioButtonTokens.setObjectName(_fromUtf8("radioButtonTokens"))
        self.gridLayout_2.addWidget(self.radioButtonTokens, 0, 0, 1, 1)
        self.radioButtonComponents = QtGui.QRadioButton(self.layoutWidget3)
        self.radioButtonComponents.setObjectName(_fromUtf8("radioButtonComponents"))
        self.gridLayout_2.addWidget(self.radioButtonComponents, 0, 2, 1, 2)
        self.radioButtonNetworks = QtGui.QRadioButton(self.layoutWidget3)
        self.radioButtonNetworks.setObjectName(_fromUtf8("radioButtonNetworks"))
        self.gridLayout_2.addWidget(self.radioButtonNetworks, 1, 0, 1, 1)
        self.radioButtonInterfaces = QtGui.QRadioButton(self.layoutWidget3)
        self.radioButtonInterfaces.setObjectName(_fromUtf8("radioButtonInterfaces"))
        self.gridLayout_2.addWidget(self.radioButtonInterfaces, 1, 1, 1, 1)
        self.radioButtonIntrafaces = QtGui.QRadioButton(self.layoutWidget3)
        self.radioButtonIntrafaces.setObjectName(_fromUtf8("radioButtonIntrafaces"))
        self.gridLayout_2.addWidget(self.radioButtonIntrafaces, 1, 2, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        self.stackedProperties.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupComponents.setTitle(_translate("MainWindow", "components", None))
        self.groupShapes.setTitle(_translate("MainWindow", "shapes", None))
        self.groupObjects.setTitle(_translate("MainWindow", "graph objects", None))
        self.groupPhase.setTitle(_translate("MainWindow", "phase", None))
        self.comboEditorPhase.setToolTip(_translate("MainWindow", "graph editor phases -- choose", None))
        self.radioButtonNetworksComponents.setText(_translate("MainWindow", "networks", None))
        self.radioButtonInterfacesComponents.setText(_translate("MainWindow", "interface", None))
        self.radioButtonIntrafacesComponents.setText(_translate("MainWindow", "intraface", None))
        self.groupNetworksComponents.setTitle(_translate("MainWindow", "networks", None))
        self.groupComponentEditor.setTitle(_translate("MainWindow", "Component editor", None))
        self.label_31.setText(_translate("MainWindow", "parameters", None))
        self.label_32.setText(_translate("MainWindow", "Ellipse", None))
        self.label_33.setText(_translate("MainWindow", "width", None))
        self.label_34.setText(_translate("MainWindow", "height", None))
        self.groupBoxEllipseColour.setTitle(_translate("MainWindow", "colour", None))
        self.label_35.setText(_translate("MainWindow", "line", None))
        self.groupBoxLineColour.setTitle(_translate("MainWindow", "colour", None))
        self.label_36.setText(_translate("MainWindow", "width", None))
        self.label_37.setText(_translate("MainWindow", "style", None))
        self.label_38.setText(_translate("MainWindow", "text", None))
        self.label_39.setText(_translate("MainWindow", "panel", None))
        self.groupBoxPanelColour.setTitle(_translate("MainWindow", "colour", None))
        self.label_49.setText(_translate("MainWindow", "width", None))
        self.label_40.setText(_translate("MainWindow", "height", None))
        self.groupPosition.setTitle(_translate("MainWindow", "relative position of component", None))
        self.label_45.setText(_translate("MainWindow", "x", None))
        self.label_46.setText(_translate("MainWindow", "y", None))
        self.checkMovable.setText(_translate("MainWindow", "movable", None))
        self.groupActions.setTitle(_translate("MainWindow", "actions", None))
        self.label_47.setText(_translate("MainWindow", "available", None))
        self.label_48.setText(_translate("MainWindow", "chosen", None))
        self.pushExplainActions.setText(_translate("MainWindow", "explain", None))
        self.groupLayer.setTitle(_translate("MainWindow", "layer", None))
        self.radioMainPanel.setText(_translate("MainWindow", "main panel", None))
        self.radioSidePanel.setText(_translate("MainWindow", "side panels", None))
        self.radioNetwork.setText(_translate("MainWindow", "network", None))
        self.radioArc.setText(_translate("MainWindow", "arc", None))
        self.radioKnot.setText(_translate("MainWindow", "knot", None))
        self.radioNode.setText(_translate("MainWindow", "node", None))
        self.radioProperty.setText(_translate("MainWindow", "property", None))
        self.radioText.setText(_translate("MainWindow", "text", None))
        self.groupStateApplication.setTitle(_translate("MainWindow", "Selectors", None))
        self.label_29.setText(_translate("MainWindow", "state", None))
        self.label_28.setText(_translate("MainWindow", "application", None))
        self.groupNetworks.setTitle(_translate("MainWindow", "networks", None))
        self.groupBoxNetworkColour.setTitle(_translate("MainWindow", "colour", None))
        self.groupControls.setTitle(_translate("MainWindow", "controls", None))
        self.pushCopyPhaseToPhases.setText(_translate("MainWindow", "copy", None))
        self.pushSave.setText(_translate("MainWindow", "save", None))
        self.pushSaveBackup.setText(_translate("MainWindow", "save + back", None))
        self.labelOntology.setText(_translate("MainWindow", "TextLabel", None))
        self.groupTokens.setTitle(_translate("MainWindow", "tokens", None))
        self.groupBoxTokenColour.setTitle(_translate("MainWindow", "colour", None))
        self.groupMain.setTitle(_translate("MainWindow", "main", None))
        self.radioButtonTokens.setText(_translate("MainWindow", "tokens", None))
        self.radioButtonComponents.setText(_translate("MainWindow", "components", None))
        self.radioButtonNetworks.setText(_translate("MainWindow", "networks", None))
        self.radioButtonInterfaces.setText(_translate("MainWindow", "interface", None))
        self.radioButtonIntrafaces.setText(_translate("MainWindow", "intraface", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))

