# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/heinz/1_Gits/ProcessModeller/ProcessModeller_v5_01/packages/AutomataEditor/editor_automata_dialog.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore
from PyQt4 import QtGui

try:
  _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
  def _fromUtf8(s):
    return s

try:
  _encoding = QtGui.QApplication.UnicodeUTF8


  def _translate(context, text, disambig):
    return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
  def _translate(context, text, disambig):
    return QtGui.QApplication.translate(context, text, disambig)


class Ui_Dialog(object):
  def setupUi(self, Dialog):
    Dialog.setObjectName(_fromUtf8("Dialog"))
    Dialog.setWindowModality(QtCore.Qt.NonModal)
    Dialog.resize(1224, 968)
    sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
    Dialog.setSizePolicy(sizePolicy)
    Dialog.setSizeIncrement(QtCore.QSize(10, 10))
    self.tabWidget = QtGui.QTabWidget(Dialog)
    self.tabWidget.setGeometry(QtCore.QRect(10, 70, 1201, 881))
    self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
    self.tab_mouse_automat = QtGui.QWidget()
    self.tab_mouse_automat.setObjectName(_fromUtf8("tab_mouse_automat"))
    self.groupSelections = QtGui.QGroupBox(self.tab_mouse_automat)
    self.groupSelections.setGeometry(QtCore.QRect(10, 10, 1021, 281))
    self.groupSelections.setObjectName(_fromUtf8("groupSelections"))
    self.layoutWidget = QtGui.QWidget(self.groupSelections)
    self.layoutWidget.setGeometry(QtCore.QRect(680, 30, 321, 241))
    self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
    self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget)
    self.verticalLayout_4.setMargin(0)
    self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
    self.label_3 = QtGui.QLabel(self.layoutWidget)
    self.label_3.setAlignment(QtCore.Qt.AlignCenter)
    self.label_3.setObjectName(_fromUtf8("label_3"))
    self.verticalLayout_4.addWidget(self.label_3)
    self.listCursors = QtGui.QListWidget(self.layoutWidget)
    self.listCursors.setObjectName(_fromUtf8("listCursors"))
    self.verticalLayout_4.addWidget(self.listCursors)
    self.layoutWidget1 = QtGui.QWidget(self.groupSelections)
    self.layoutWidget1.setGeometry(QtCore.QRect(16, 30, 651, 241))
    self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
    self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget1)
    self.horizontalLayout.setMargin(0)
    self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
    self.verticalLayout = QtGui.QVBoxLayout()
    self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
    self.label = QtGui.QLabel(self.layoutWidget1)
    self.label.setAlignment(QtCore.Qt.AlignCenter)
    self.label.setObjectName(_fromUtf8("label"))
    self.verticalLayout.addWidget(self.label)
    self.listSelectState = QtGui.QListWidget(self.layoutWidget1)
    self.listSelectState.setObjectName(_fromUtf8("listSelectState"))
    self.verticalLayout.addWidget(self.listSelectState)
    self.horizontalLayout.addLayout(self.verticalLayout)
    self.verticalLayout_3 = QtGui.QVBoxLayout()
    self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
    self.label_2 = QtGui.QLabel(self.layoutWidget1)
    self.label_2.setAlignment(QtCore.Qt.AlignCenter)
    self.label_2.setObjectName(_fromUtf8("label_2"))
    self.verticalLayout_3.addWidget(self.label_2)
    self.listActions = QtGui.QListWidget(self.layoutWidget1)
    self.listActions.setObjectName(_fromUtf8("listActions"))
    self.verticalLayout_3.addWidget(self.listActions)
    self.horizontalLayout.addLayout(self.verticalLayout_3)
    self.verticalLayout_2 = QtGui.QVBoxLayout()
    self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
    self.label_4 = QtGui.QLabel(self.layoutWidget1)
    self.label_4.setAlignment(QtCore.Qt.AlignCenter)
    self.label_4.setObjectName(_fromUtf8("label_4"))
    self.verticalLayout_2.addWidget(self.label_4)
    self.listStates = QtGui.QListWidget(self.layoutWidget1)
    self.listStates.setObjectName(_fromUtf8("listStates"))
    self.verticalLayout_2.addWidget(self.listStates)
    self.horizontalLayout.addLayout(self.verticalLayout_2)
    self.tableState = QtGui.QTableWidget(self.tab_mouse_automat)
    self.tableState.setGeometry(QtCore.QRect(30, 310, 1141, 521))
    self.tableState.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
    self.tableState.setObjectName(_fromUtf8("tableState"))
    self.tableState.setColumnCount(6)
    self.tableState.setRowCount(0)
    item = QtGui.QTableWidgetItem()
    self.tableState.setHorizontalHeaderItem(0, item)
    item = QtGui.QTableWidgetItem()
    self.tableState.setHorizontalHeaderItem(1, item)
    item = QtGui.QTableWidgetItem()
    self.tableState.setHorizontalHeaderItem(2, item)
    item = QtGui.QTableWidgetItem()
    self.tableState.setHorizontalHeaderItem(3, item)
    item = QtGui.QTableWidgetItem()
    self.tableState.setHorizontalHeaderItem(4, item)
    item = QtGui.QTableWidgetItem()
    self.tableState.setHorizontalHeaderItem(5, item)
    self.tableState.horizontalHeader().setDefaultSectionSize(150)
    self.tabWidget.addTab(self.tab_mouse_automat, _fromUtf8(""))
    self.tab_key_automat = QtGui.QWidget()
    self.tab_key_automat.setObjectName(_fromUtf8("tab_key_automat"))
    self.layoutWidget_2 = QtGui.QWidget(self.tab_key_automat)
    self.layoutWidget_2.setGeometry(QtCore.QRect(10, 300, 1001, 461))
    self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
    self.gridlayout = QtGui.QGridLayout(self.layoutWidget_2)
    self.gridlayout.setMargin(5)
    self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
    self.tableKeyAutomaton = QtGui.QTableWidget(self.layoutWidget_2)
    self.tableKeyAutomaton.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
    self.tableKeyAutomaton.setObjectName(_fromUtf8("tableKeyAutomaton"))
    self.tableKeyAutomaton.setColumnCount(3)
    self.tableKeyAutomaton.setRowCount(0)
    item = QtGui.QTableWidgetItem()
    self.tableKeyAutomaton.setHorizontalHeaderItem(0, item)
    item = QtGui.QTableWidgetItem()
    self.tableKeyAutomaton.setHorizontalHeaderItem(1, item)
    item = QtGui.QTableWidgetItem()
    self.tableKeyAutomaton.setHorizontalHeaderItem(2, item)
    self.tableKeyAutomaton.horizontalHeader().setDefaultSectionSize(150)
    self.gridlayout.addWidget(self.tableKeyAutomaton, 0, 0, 1, 3)
    self.pushAddKey = QtGui.QPushButton(self.layoutWidget_2)
    self.pushAddKey.setObjectName(_fromUtf8("pushAddKey"))
    self.gridlayout.addWidget(self.pushAddKey, 1, 0, 1, 1)
    self.pushDeleteKey = QtGui.QPushButton(self.layoutWidget_2)
    self.pushDeleteKey.setObjectName(_fromUtf8("pushDeleteKey"))
    self.gridlayout.addWidget(self.pushDeleteKey, 1, 1, 1, 1)
    spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
    self.gridlayout.addItem(spacerItem, 1, 2, 1, 1)
    self.groupSelection = QtGui.QGroupBox(self.tab_key_automat)
    self.groupSelection.setGeometry(QtCore.QRect(10, 10, 1031, 281))
    self.groupSelection.setObjectName(_fromUtf8("groupSelection"))
    self.layoutWidget2 = QtGui.QWidget(self.groupSelection)
    self.layoutWidget2.setGeometry(QtCore.QRect(50, 20, 951, 231))
    self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
    self.gridLayout = QtGui.QGridLayout(self.layoutWidget2)
    self.gridLayout.setMargin(0)
    self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
    self.label_21 = QtGui.QLabel(self.layoutWidget2)
    self.label_21.setAlignment(QtCore.Qt.AlignCenter)
    self.label_21.setObjectName(_fromUtf8("label_21"))
    self.gridLayout.addWidget(self.label_21, 0, 0, 1, 1)
    self.label_20 = QtGui.QLabel(self.layoutWidget2)
    self.label_20.setAlignment(QtCore.Qt.AlignCenter)
    self.label_20.setObjectName(_fromUtf8("label_20"))
    self.gridLayout.addWidget(self.label_20, 0, 1, 1, 1)
    self.label_19 = QtGui.QLabel(self.layoutWidget2)
    self.label_19.setAlignment(QtCore.Qt.AlignCenter)
    self.label_19.setObjectName(_fromUtf8("label_19"))
    self.gridLayout.addWidget(self.label_19, 0, 2, 1, 1)
    self.listKeysForKeyAutomaton = QtGui.QListWidget(self.layoutWidget2)
    self.listKeysForKeyAutomaton.setObjectName(_fromUtf8("listKeysForKeyAutomaton"))
    self.gridLayout.addWidget(self.listKeysForKeyAutomaton, 1, 0, 1, 1)
    self.listStatesForKeyAutomaton = QtGui.QListWidget(self.layoutWidget2)
    self.listStatesForKeyAutomaton.setObjectName(_fromUtf8("listStatesForKeyAutomaton"))
    self.gridLayout.addWidget(self.listStatesForKeyAutomaton, 1, 1, 1, 1)
    self.listActionsForKeyAutomaton = QtGui.QListWidget(self.layoutWidget2)
    self.listActionsForKeyAutomaton.setObjectName(_fromUtf8("listActionsForKeyAutomaton"))
    self.gridLayout.addWidget(self.listActionsForKeyAutomaton, 1, 2, 1, 1)
    self.tabWidget.addTab(self.tab_key_automat, _fromUtf8(""))
    self.groupBox = QtGui.QGroupBox(Dialog)
    self.groupBox.setGeometry(QtCore.QRect(10, 0, 271, 61))
    self.groupBox.setObjectName(_fromUtf8("groupBox"))
    self.comboPhase = QtGui.QComboBox(self.groupBox)
    self.comboPhase.setGeometry(QtCore.QRect(10, 20, 151, 22))
    self.comboPhase.setObjectName(_fromUtf8("comboPhase"))
    self.pushSaveAutomaton = QtGui.QPushButton(Dialog)
    self.pushSaveAutomaton.setGeometry(QtCore.QRect(500, 10, 71, 25))
    self.pushSaveAutomaton.setObjectName(_fromUtf8("pushSaveAutomaton"))
    self.checkBoxBackup = QtGui.QCheckBox(Dialog)
    self.checkBoxBackup.setGeometry(QtCore.QRect(630, 10, 93, 23))
    self.checkBoxBackup.setObjectName(_fromUtf8("checkBoxBackup"))
    self.checkBoxInstall = QtGui.QCheckBox(Dialog)
    self.checkBoxInstall.setGeometry(QtCore.QRect(630, 30, 93, 23))
    self.checkBoxInstall.setObjectName(_fromUtf8("checkBoxInstall"))
    self.pushLaTex = QtGui.QPushButton(Dialog)
    self.pushLaTex.setGeometry(QtCore.QRect(500, 50, 97, 27))
    self.pushLaTex.setObjectName(_fromUtf8("pushLaTex"))

    self.retranslateUi(Dialog)
    self.tabWidget.setCurrentIndex(0)
    QtCore.QMetaObject.connectSlotsByName(Dialog)

  def retranslateUi(self, Dialog):
    Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
    self.groupSelections.setTitle(_translate("Dialog", "Selections", None))
    self.label_3.setText(_translate("Dialog", "cusor", None))
    self.label.setText(_translate("Dialog", "selector", None))
    self.label_2.setText(_translate("Dialog", "action", None))
    self.label_4.setText(_translate("Dialog", "state", None))
    item = self.tableState.horizontalHeaderItem(0)
    item.setText(_translate("Dialog", "object", None))
    item = self.tableState.horizontalHeaderItem(1)
    item.setText(_translate("Dialog", "mouse left", None))
    item = self.tableState.horizontalHeaderItem(2)
    item.setText(_translate("Dialog", "left: next state", None))
    item = self.tableState.horizontalHeaderItem(3)
    item.setText(_translate("Dialog", "mouse right", None))
    item = self.tableState.horizontalHeaderItem(4)
    item.setText(_translate("Dialog", "right: mouse", None))
    item = self.tableState.horizontalHeaderItem(5)
    item.setText(_translate("Dialog", "cursor", None))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_mouse_automat), _translate("Dialog", "mouse", None))
    item = self.tableKeyAutomaton.horizontalHeaderItem(0)
    item.setText(_translate("Dialog", "key", None))
    item = self.tableKeyAutomaton.horizontalHeaderItem(1)
    item.setText(_translate("Dialog", "next state", None))
    item = self.tableKeyAutomaton.horizontalHeaderItem(2)
    item.setText(_translate("Dialog", "GUI action", None))
    self.pushAddKey.setText(_translate("Dialog", "add key", None))
    self.pushDeleteKey.setText(_translate("Dialog", "delete key", None))
    self.groupSelection.setTitle(_translate("Dialog", "Selection", None))
    self.label_21.setText(_translate("Dialog", "key", None))
    self.label_20.setText(_translate("Dialog", "state", None))
    self.label_19.setText(_translate("Dialog", "action", None))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_key_automat), _translate("Dialog", "key", None))
    self.groupBox.setTitle(_translate("Dialog", "select phase", None))
    self.pushSaveAutomaton.setText(_translate("Dialog", "save", None))
    self.checkBoxBackup.setText(_translate("Dialog", "backup", None))
    self.checkBoxInstall.setText(_translate("Dialog", "install", None))
    self.pushLaTex.setText(_translate("Dialog", "LaTex", None))
